name: Windows Repro

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  repro:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Print diagnostics
        shell: pwsh
        run: |
          $PSVersionTable
          node -v
          npm -v
          git --version
          echo "Path sep: [\\]"

      - name: Clean install
        run: yarn install

      - name: Run repro
        run: npm test

      - name: Upload artifacts (env + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-repro-${{ matrix.node }}
          path: |
            artifacts/**
            npm-debug.log*
            ./*.log
